# Generated by Django 3.0.7 on 2020-07-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_auto_20200705_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='link',
            new_name='file',
        ),
    ]
