# Generated by Django 3.0.7 on 2020-07-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0003_auto_20200707_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='link',
        ),
    ]
