# Generated by Django 3.0.7 on 2020-07-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
